nodes:
- input.recorded:
    input_dir: C:/Users/benis/Documents/GitHub/AutoAttend/peekingduck/temp/images/attendance.jpg
- model.mtcnn
- custom_nodes.model.face_recognition
- custom_nodes.output.writer